Checkpoint 1
nexus-chebykin/ATP_incident pull request #7
Opened 2022-03-20 16:37 UTC by nexus-chebykin

1) UML-диаграмма классов
2) Реализована эта структура классов
3) Реализованы методы внутренней логики
4) До MVP не хватает только основного сценария игры
5) Планы на будущее: 
- Доделать до MVP
- Реализовать более красивый консольный интерфейс
- Реализовать бота
- Графический интерфейс (?)

2022-04-01 09:54 UTC, MarkTiukov requested changes
Надо исправить ридми

2022-04-01 22:45 UTC, MarkTiukov requested changes
Файлы не должны называться с пробелами. Если уж используете нижние подчеркивания, то приведите все названия в `snake_case`. Названия классов в `PascalCase`. Названия функций в `camelCase` или `PascalCase`, но надо один какой-то выбрать и везде так называть.  Один файл = один класс (исключения: енамы, приватные классы)

Не надо везде использовать структуру. Структура используется для объектов, где пара публичных полей будет, максимум перегрузка операторов. Всё остальное класс, с приватными полями и т.д.

Разбейте код по папкам: на верху `src\`, внутри весь код, разделенный по логичным папкам, хранящие файлы на одну тему, тем самым образуя некоторые "модули" проекта

2022-04-01 22:45 UTC, MarkTiukov commented on GameMaster.h
> +    void play_DoTurns();
Сами названия не намекают, что стоит выделить дополнительные классы?

2022-04-01 22:45 UTC, MarkTiukov commented on Ship and Cell.h
> +    Ship(vector<Cell*>& cells);
должен быть класс, а не структура

2022-04-01 22:45 UTC, MarkTiukov commented on Ship and Cell.h
> +};
должен быть класс, а не структура

2022-04-01 22:45 UTC, MarkTiukov commented on Simplest_GUI.cpp
> +using std::wcout;
юзинги нельзя

2022-04-01 22:45 UTC, MarkTiukov commented on Simplest_GUI.cpp
> +        }
Почему определение функции в хедере?

2022-04-01 22:45 UTC, MarkTiukov commented on Simplest_GUI.cpp
> +        }
Почему ве эти определения в хедере?

2022-04-01 22:45 UTC, MarkTiukov commented on Player.h
> +#include "GUI_Interface.h"
Почему инклюд тут?

2022-04-01 22:45 UTC, MarkTiukov commented on Player_Settings.h
> +};
ужас название

2022-04-01 22:45 UTC, MarkTiukov commented on Ship and Cell.h
> +    enum State {
Что здесь вообще происходит

2022-04-01 22:45 UTC, MarkTiukov commented on Global_Settings.h
> +struct Global_Settings {
класс

2022-04-01 22:45 UTC, MarkTiukov commented on Player.h
> +
что это? зачем?

2022-04-01 22:45 UTC, MarkTiukov commented on Player.h
> +struct Player {
не структура, а класс

2022-04-03 15:48 UTC, Fas0u1er commented on GameMaster.h
> +    void play_DoTurns();
Это был скорее рудимент, убрал

2022-04-03 15:48 UTC, Fas0u1er commented on Ship and Cell.h
> +    Ship(vector<Cell*>& cells);
Сделал

2022-04-03 15:48 UTC, Fas0u1er commented on Ship and Cell.h
> +};
Сделал

2022-04-03 15:55 UTC, Fas0u1er commented on Simplest_GUI.cpp
> +using std::wcout;
Это дебажный GUI, зря его запушили, ко второму дедлайну будет реализация нормальная, без юзингов)

2022-04-03 15:57 UTC, Fas0u1er commented on Player.h
> +#include "GUI_Interface.h"
Случайно осталось, убрано

2022-04-03 15:57 UTC, Fas0u1er commented on Player_Settings.h
> +};
Все названия файлов\классов\функций из внутренней логики сделал однотипно-адекватными

2022-04-03 15:58 UTC, Fas0u1er commented on Simplest_GUI.cpp
> +        }
Это дебажный GUI, зря его запушили, ко второму дедлайну будет реализация нормальная

2022-04-03 15:58 UTC, Fas0u1er commented on Simplest_GUI.cpp
> +        }
Это дебажный GUI, зря его запушили, ко второму дедлайну будет реализация нормальная

2022-04-03 15:58 UTC, Fas0u1er commented on Player.h
> +
убрано

2022-04-03 15:59 UTC, Fas0u1er commented on Player.h
> +struct Player {
Сделал все классами

2022-04-03 16:11 UTC, Fas0u1er commented
Все замечания вроде бы исправил, добавил фабрику кораблей, билдер досок, нормальные названия всего, что относится к логике, разложил файлы по директориям. Делать Board интерфейсом, как мне кажется смысла нет, т.к. даже если мы соберемся делать доски непрямоугольной формы(а этого в планах пока нет), то они все равно будут на основе сетки, и это лучше будет сделать как прямоугольную доску с некоторыми клетками, помеченными как "скала" например. К Ship тоже интерфес не подходит, потому что со стороны логики корабль - вектор клеток, и его форма не влияет на его поведение, кроме как в момент его построения. Поэтому вместо копипасты с интерфесом\реализациями добавил тип корабля как енам.

2022-04-03 16:13 UTC, Fas0u1er commented
Все замечания вроде бы исправил, добавил фабрику кораблей, билдер досок, нормальные названия всего, что относится к логике, разложил файлы по директориям. Делать Board интерфейсом, как мне кажется смысла нет, т.к. даже если мы соберемся делать доски непрямоугольной формы(а этого в планах пока нет), то они все равно будут на основе сетки, и это лучше будет сделать как прямоугольную доску с некоторыми клетками, помеченными как "скала" например. К Ship тоже интерфес не подходит, потому что со стороны логики корабль - вектор клеток, и его форма не влияет на его поведение, кроме как в момент его построения. Поэтому вместо копипасты с интерфесом\реализациями добавил тип корабля как енам.

2022-04-12 12:13 UTC, MarkTiukov commented
> даже если мы соберемся делать доски непрямоугольной формы(а этого в планах пока нет)

Если хотите фулл -- должно быть

> К Ship тоже интерфес не подходит, потому что со стороны логики корабль - вектор клеток, и его форма не влияет на его поведение, кроме как в момент его построения

Так ты же не знаешь наперед, какие новшества будут. Можно корабли не только разных формы делать, а, например, бронированные (с доп жизнью). Для полного балла что-то такое понадобиться

2022-04-12 12:17 UTC, MarkTiukov approved these changes
Поставлю по 9ке. Коммент про корабли учтите, если хотите дальше максимальный балл. 

## К следующему чекпоинту

Обязательно в ридми описание новых вещей, как запускать проект, кто что делал (тут напоминаю, что суть не в разбросе задач, а разделении ответственности по модулям)

Данный пулл-реквест сами можете мерджить

2022-04-12 12:38 UTC, merged