Checkpoint 2
nexus-chebykin/ATP_incident pull request #8
Opened 2022-04-18 21:07 UTC by nexus-chebykin

По сравнению с чекпоинт 1: Доработано меню и интерфейс, появились боты, стало можно играть. Поздно сделали PR, потому что сначала надо было исправить замечания по чекпоинту 1.

2022-05-04 21:46 UTC, MarkTiukov requested changes

2022-05-04 21:46 UTC, MarkTiukov commented on src/GUI/GUI.h
> +
Зачем?)

2022-05-04 21:46 UTC, MarkTiukov commented on src/GUI/SimplestGUI.cpp
Лучше без юзингов из стд

2022-05-04 21:46 UTC, MarkTiukov commented on src/GUI/SimplestGUI.cpp
>  using std::cin;
лучше без юзингов из стд

2022-05-04 21:46 UTC, MarkTiukov commented on src/board/Board.h
> +class Ship;
зачем

2022-05-04 21:46 UTC, MarkTiukov commented on src/board/Board.h
> +    [[nodiscard]] int shipCount() const;
Зачем тут `nodiscard`?

2022-05-04 21:46 UTC, MarkTiukov commented on src/board/Board.h
> +    [[nodiscard]] int shipCount() const;
Какой смысл вызывать геттер поля, если им не воспользуются?

2022-05-04 21:46 UTC, MarkTiukov commented on src/board/BoardBuilder.cpp
>      return instance;
Это попытка в Singleton?

2022-05-04 21:46 UTC, MarkTiukov commented on src/board/BoardBuilder.cpp
>      return instance;
Иначе зачем?..

2022-05-04 21:46 UTC, MarkTiukov commented on src/board/BoardBuilder.h
зачем

2022-05-04 21:46 UTC, MarkTiukov commented on src/board/Cell.h
> +class SimpleShip;
зачем

2022-05-04 21:46 UTC, MarkTiukov commented on src/board/Cell.h
> +    [[nodiscard]] bool isOkToAttack() const;
Аналогично `nodiscard` выше -- не понял, зачем тут

2022-05-04 21:46 UTC, MarkTiukov commented on src/board/RectangleBoard.h
> +class Ship;
зачем

2022-05-04 21:46 UTC, MarkTiukov commented on src/board/RectangleBoard.h
> +    [[nodiscard]] bool withinBorders(Position) const override;
Зачем `nodiscard`?

2022-05-04 21:46 UTC, MarkTiukov commented on src/game_master/GameMaster.h
> +class GUI;
Зачем?

2022-05-04 21:46 UTC, MarkTiukov commented on src/menu_displayer/MenuDisplayer.h
> +class PlayerSettings;
зачем

2022-05-04 21:46 UTC, MarkTiukov commented on src/player/HumanPlayer.h
> +
зачем

2022-05-04 21:46 UTC, MarkTiukov commented on src/player/Player.h
> +class Position;
зачем

2022-05-04 21:46 UTC, MarkTiukov commented on src/player/Player.h
> +    [[nodiscard]] std::string getName() const;
Зачем `nodiscard`

2022-05-04 21:46 UTC, MarkTiukov commented on src/player/PlayerFactory.h
> +class Player;
зачем

2022-05-05 06:33 UTC, nexus-chebykin commented on src/board/BoardBuilder.cpp
>      return instance;
Да это синглтон, и он так и используется

2022-05-05 08:20 UTC, Fas0u1er commented
Кто что делал (по сравнению с checkpoint_1):
Семен:
Консольный интерфейс, основной сценарий игры (меню настроек, игра)
Борис: 
Боты (трех сложностей)

2022-05-05 08:23 UTC, Fas0u1er commented on src/GUI/SimplestGUI.cpp
Убрано

2022-05-12 23:24 UTC, MarkTiukov approved these changes

2022-05-12 23:24 UTC, merged